plugins {
    // see https://fabricmc.net/develop/ for new versions
    // see https://docs.fabricmc.net/develop/porting/next for 26.1 changes to plugin id
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version "${moddev_version}" apply false
}

allprojects {
    repositories {
        maven {
            name = "Mojang"
            url = uri("https://libraries.minecraft.net")
        }
    }
}
repositories {

    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
    }
    maven {
        name = "JourneyMap (Public)"
        url = "https://jm.gserv.me/repository/maven-public/"
    }
    // New maven repo our API. Please switch to this maven.
    // We will continue to upload to jm.gserve.me, but that maven goes down more than we'd like.
    maven {
        name = "New JourneyMap Maven"
        url = 'https://maven.blamejared.com'
    }
    // Optional cursemaven
    maven {
        name = "Curse Maven"
        url "https://www.cursemaven.com"
    }
    // Optional Modrinth Maven
    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
    }
}