# Project
# fuck this version number
version=1.2.0-1.21.1-rc.final.rev.2
group=me.brynview.navidrohim
java_version=21

# Common
minecraft_version=1.21.1
mod_name=JourneyMap Waypoint Syncing
mod_author=Navid Rohim
mod_id=jmws
license=MIT
credits=Kay (Somali translations), Dempy (Polish translations)
description=This mod allows you to save waypoints on JourneyMap between multiple devices via the player/account UUID on the server
minecraft_version_range=1.21.1

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions (does not have 1.21.10 mappings)
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric https://fabricmc.net/develop/
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.17.3

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=52.1.0
forge_loader_version_range=[52,)

# NeoForge https://neoforged.net/ (neoforge) https://projects.neoforged.net/neoforged/neoform (neoform)
neoforge_version=21.1.209
neoforge_loader_version_range=[4,)
neo_form_version=1.21.1-20240808.144430
moddev_version=2.0.105

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# JourneyMap Variables (and related)
journeymap_api_version = 2.0.0-1.21.1-SNAPSHOT
common_networking_version = 1.0.18-1.21.1