plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '7.0.0-beta.55'
}

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    mavenLocal()
}

def baseName = "${mod_id}-forge"
base.archivesName = baseName

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        register('client') {
            workingDir.convention layout.projectDirectory.dir('run/client')
        }

        register('server') {
            workingDir.convention layout.projectDirectory.dir('run/server')
            args '--nogui'
        }
    }

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}");
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'

    compileOnly group: 'info.journeymap', name: 'journeymap-api-forge', version: project.journeymap_api_version, changing: true
    implementation "mysticdrew:common-networking-forge:${common_networking_version}"

}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
